In [23]:
import numpy as np 
import pandas as pd
import tensorflow as tf
#import pickle


import seaborn as sb
import matplotlib.pyplot as mp
import plotly.express as px

import plotly.graph_objects as go
from plotly.subplots import make_subplots 
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

import statsmodels.api as stm
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import MinMaxScaler

In [56]:

df= pd.read_csv('Churn_Modelling.csv')
df.drop(['RowNumber','CustomerId','Surname','Geography','Gender'],inplace=True,axis=1)
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [57]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0
9996,516,35,10,57369.61,1,1,1,101699.77,0
9997,709,36,7,0.00,1,0,1,42085.58,1
9998,772,42,3,75075.31,2,1,0,92888.52,1
9999,792,28,4,130142.79,1,1,0,38190.78,0

In [58]:
df.iloc[:, 0:-1]

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64
9996,516,35,10,57369.61,1,1,1,101699.77
9997,709,36,7,0.00,1,0,1,42085.58
9998,772,42,3,75075.31,2,1,0,92888.52
9999,792,28,4,130142.79,1,1,0,38190.78

In [59]:
print(X)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1
1             608   41       1   83807.86              1          0
2             502   42       8  159660.80              3          1
3             699   39       1       0.00              2          0
4             850   43       2  125510.82              1          1
...           ...  ...     ...        ...            ...        ...
9995          771   39       5       0.00              2          1
9996          516   35      10   57369.61              1          1
9997          709   36       7       0.00              1          0
9998          772   42       3   75075.31              2          1
9999          792   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary
0                  1        101348.88
1                  1        112542.58
2                  0        113931.57
3                  0         93826.63
4                  1         79084.10
...              ...              ...
9995               0         96270.64
9996               1        101699.77
9997               1         42085.58
9998               0         92888.52
9999               0         38190.78

[10000 rows x 8 columns]

In [60]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [61]:
#Encoding categorical data
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#X[:, 2] = le.fit_transform(X[:, 2])

In [62]:
print(X)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1
1             608   41       1   83807.86              1          0
2             502   42       8  159660.80              3          1
3             699   39       1       0.00              2          0
4             850   43       2  125510.82              1          1
...           ...  ...     ...        ...            ...        ...
9995          771   39       5       0.00              2          1
9996          516   35      10   57369.61              1          1
9997          709   36       7       0.00              1          0
9998          772   42       3   75075.31              2          1
9999          792   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary
0                  1        101348.88
1                  1        112542.58
2                  0        113931.57
3                  0         93826.63
4                  1         79084.10
...              ...              ...
9995               0         96270.64
9996               1        101699.77
9997               1         42085.58
9998               0         92888.52
9999               0         38190.78

[10000 rows x 8 columns]

In [63]:
#one hot encoder for "geography" colum
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [64]:
print(X)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1
1             608   41       1   83807.86              1          0
2             502   42       8  159660.80              3          1
3             699   39       1       0.00              2          0
4             850   43       2  125510.82              1          1
...           ...  ...     ...        ...            ...        ...
9995          771   39       5       0.00              2          1
9996          516   35      10   57369.61              1          1
9997          709   36       7       0.00              1          0
9998          772   42       3   75075.31              2          1
9999          792   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary
0                  1        101348.88
1                  1        112542.58
2                  0        113931.57
3                  0         93826.63
4                  1         79084.10
...              ...              ...
9995               0         96270.64
9996               1        101699.77
9997               1         42085.58
9998               0         92888.52
9999               0         38190.78

[10000 rows x 8 columns]

In [65]:
#split the data into training set  and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [66]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
#Building the ANN
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [68]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [69]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [70]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [71]:
#Training the ANN
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [72]:
#Training the ANN on the training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6154 - accuracy: 0.7104
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4916 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4662 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4533 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4443 - accuracy: 0.7968
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4367 - accuracy: 0.7983
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4286 - accuracy: 0.8015
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4194 - accuracy: 0.8062
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4106 - accuracy: 0.8123
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4024 - accuracy: 0.8152
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3954 - accuracy: 0.8167
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3897 - accuracy: 0.8185
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3853 - accuracy: 0.8194
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3812 - accuracy: 0.8192
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3777 - accuracy: 0.8204
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3744 - accuracy: 0.8385
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8451
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3694 - accuracy: 0.8480
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3675 - accuracy: 0.8493
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3662 - accuracy: 0.8505
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3648 - accuracy: 0.8509
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3635 - accuracy: 0.8504
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3622 - accuracy: 0.8503
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3614 - accuracy: 0.8509
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3605 - accuracy: 0.8504
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3597 - accuracy: 0.8512
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3595 - accuracy: 0.8519
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8518
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3581 - accuracy: 0.8535
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3574 - accuracy: 0.8533
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3568 - accuracy: 0.8539
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3564 - accuracy: 0.8537
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3561 - accuracy: 0.8539
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3554 - accuracy: 0.8545
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8522
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3548 - accuracy: 0.8534
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3546 - accuracy: 0.8535
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8541
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3539 - accuracy: 0.8553
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3537 - accuracy: 0.8554
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3534 - accuracy: 0.8531
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8554
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8551
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8544: 0s - loss: 0.3538 - accuracy: 0.
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3524 - accuracy: 0.8554
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8543
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8547
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3523 - accuracy: 0.8565
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3522 - accuracy: 0.8545
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3520 - accuracy: 0.8555
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8545
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8556
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8549
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3520 - accuracy: 0.8549
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3515 - accuracy: 0.8551
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3516 - accuracy: 0.8543
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8554
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8555
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3510 - accuracy: 0.8561
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8551
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8551
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8560
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3510 - accuracy: 0.8546
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8556
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8540
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3509 - accuracy: 0.8551
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8558
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.8559
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3505 - accuracy: 0.8560
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3505 - accuracy: 0.8543
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8555
Epoch 72/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3504 - accuracy: 0.8560
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8556
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8565
Epoch 75/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3503 - accuracy: 0.8554
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3501 - accuracy: 0.8562
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3503 - accuracy: 0.8554
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8553
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3501 - accuracy: 0.8576
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8556
Epoch 81/100

250/250 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8560
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3498 - accuracy: 0.8561
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8547
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8555
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3495 - accuracy: 0.8546
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3498 - accuracy: 0.8559
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3494 - accuracy: 0.8559
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8558
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8553
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3494 - accuracy: 0.8559
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8549
Epoch 92/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8554
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3491 - accuracy: 0.8556
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8549
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8562
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8553
Epoch 97/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8564
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8556
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8566
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8575

In [73]:
print(ann.predict(sc.transform([[ 619,42,2,0.00,1,1,101348.88,1]])) > 0.5)

[[False]]

In [74]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [75]:
#Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1531   64]
 [ 207  198]]

0.8645

In [76]:
ann.save('ANN_Model.h5')

In [77]:
#from keras.models import load_model

#ann.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'

In [78]:
#<input type="text" name="Geography"  placeholder='Geography'><br><br>
        #<input type="text" name="Gender"  placeholder='Gender'><br><br>